name: building and deploying the library management system
on: [push]

jobs:
  # building-image:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: logging into docker hub
  #       uses: docker/login-action@v3
  #       with:
  #           username: ${{ secrets.DOCKERUSER }}
  #           password: ${{ secrets.DOCKERTOKEN }}
  #     - name: build and push
  #       uses: docker/build-push-action@v5
  #       with:
  #         push: true
  #         tags: joe991/lib-management
  #     - run: echo "Image successfuly uploaded to docker hub!"
  
  deploying-application:
    # needs: building-image
    runs-on: [dev]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: deploying to dev machine
        run: docker compose up 

      - name: Check running containers
        run: docker ps

